organization:
  name: "${ORGANIZATION_NAME}"

admin:
  email: "${ADMIN_EMAIL}"
  password: "${ADMIN_PSW}"

clusters:
  - id: default
    name: My Local Kafka Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    properties:
    schemaRegistry:
      url: "$SR_SERVER"
      ignoreUntrustedCertificate: false
